apiVersion: dispatch.d2iq.io/v1alpha3
gitRepository:
  interval: 3m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/anishp55/nkp-flux
kind: GitopsRepository
kustomization:
  force: false
  interval: 5m0s
  path: ./gitops
  prune: true
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    name: flux
    namespace: infra-flux-validation
  targetNamespace: infra-flux-validation
metadata:
  generation: 1
  name: flux
  namespace: infra-flux-validation
