
name: 03 - apply idp

on:
  workflow_dispatch:

jobs:
  apply_idp:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: apply idp
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        export MGMT_HOSTNAME=$( kubectl get kommanderclusters.kommander.mesosphere.io  -n kommander host-cluster -oyaml | yq .spec.ingress.hostname )
        cat ./idps/auth0-oidc-idp.yaml | envsubst | kubectl apply -f -