
name: 02 - create idp secrets

on:
  workflow_dispatch:

jobs:
  create_secrets:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: create and label secret
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        kubectl create secret generic auth0-secret --from-literal="client-id"=${{secrets.AUTH0_CLIENT_ID}} --from-literal="client-secret"=${{secrets.AUTH0_CLIENT_SECRET}} -n kommander
        kubectl label secret auth0-secret  kommanderType=connectorSecret -n kommander