
name: apply idp

on:
  workflow_dispatch:

jobs:
  nkp_install:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: create secret
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        kubectl get nodes -o wide
        mkdir work
        cd work
        cp ../secrets/secrets.yaml .
        sed -i "s/CLIENT_ID/$AUTH0_CLIENT_ID/g" secrets.yaml
        sed -i "s/CLIENT_ID/$AUTH0_CLIENT_SECRET/g" secrets.yaml
        sed -i "s/SECRET_NAME/auth0-secret"
        kubectl apply -f secrets.yaml
        cd ../
        rm -rf work