
name: 06 - delete license

on:
  workflow_dispatch:

jobs:
  delete_license:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: apply virtual groups
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        kubectl delete license -n kommander nutanix-license