
name: 08 - external dns

on:
  workflow_dispatch:

jobs:
  external_dns:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: apply & patch external dns configMap
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        kubectl apply -f ./app-overrides/external-dns-cm.yaml
        kubectl patch appdeployment -n kommander external-dns --type merge -p '{"spec":{"configOverrides":{"name": "external-dns-config-overrides"}}}'