
name: 99 - test

on:
  workflow_dispatch:

jobs:
  nkp_install:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: install nkp
      run: |
        rm -rf work
        mkdir work
        cd work
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        echo "$${{secrets.INGRESS_CERT }}" > ingress.cert
        echo "${{ secrets.INGRESS_PEM }}" > ingress.pem
        echo "nkp version to install: $NKP_VERSION"
        echo "install timeout is set to: $TIMEOUT"
    - name: get dashboard
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        nkp get dashboard --kubeconfig ./work/$CLUSTER_NAME.conf
        rm -rf work