name: 05b - nutanix objects for velero and loki

on:
  workflow_dispatch:
    inputs:
      NUTANIX_OBJECTS_HOST:
        description: 'Nutanix Objects Host (e.g., objects.example.com)'
        required: true
        default: 'objects.nutanix.local'
      NUTANIX_OBJECTS_ACCESS_KEY:
        description: 'Nutanix Objects Acess Key'
        required: true
      NUTANIX_OBJECTS_SECRET_KEY:
        description: 'Nutanix Objects Secret Key'
        required: true

jobs:
  velero:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: create velero secret
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        source ./appdeployments/velero/velero-vars
        export PROFILEDATA=$(printf '[%s]\naws_access_key_id=%s\naws_secret_access_key=%s' \
          "${AWS_PROFILE}" \
          "${{ inputs.NUTANIX_OBJECTS_ACCESS_KEY }}" \
          "${{ inputs.NUTANIX_OBJECTS_SECRET_KEY }}" | base64 -w0)
        cat ./appdeployments/velero/velero-secret.yaml | envsubst | kubectl apply --server-side -f -

    - name: apply velero configmap
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        source ./appdeployments/velero/velero-vars
        export NUTANIX_OBJECTS_HOST="${{ inputs.NUTANIX_OBJECTS_HOST }}"
        cat ./appdeployments/velero/velero-cm.yaml | envsubst | kubectl apply --server-side -f -

    - name: velero appdeployment
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        nkp create appdeployment velero --app $(kubectl get clusterapp -A -o json | jq -r '.items[] | select(.spec.appId? == "velero") | .metadata.name') -c velero-overrides -w kommander-workspace  -oyaml --dry-run | kubectl apply -f -

    - name: create loki secret
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        source ./appdeployments/loki/loki-vars
        export NUTANIX_OBJECTS_ACCESS_KEY=$( echo "${{ inputs.NUTANIX_OBJECTS_ACCESS_KEY }}" | tr -d '\n' |base64 -w0 )
        export NUTANIX_OBJECTS_SECRET_KEY=$( echo "${{ inputs.NUTANIX_OBJECTS_SECRET_KEY }}" | tr -d '\n' |base64 -w0 )
        cat ./appdeployments/loki/loki-secret.yaml | envsubst | kubectl apply --server-side -f -

    - name: apply loki configmap
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        source ./appdeployments/loki/loki-vars
        export NUTANIX_OBJECTS_HOST="${{ inputs.NUTANIX_OBJECTS_HOST }}"
        cat ./appdeployments/loki/loki-cm.yaml | envsubst | kubectl apply --server-side -f -


    - name: grafana-loki appdeployment
      run: |
        source ${GITHUB_WORKSPACE}/nkp-vars.sh
        export PATH=$PATH:~/bin
        export KUBECONFIG=~/kubectl-configs/$CLUSTER_NAME.conf
        nkp create appdeployment grafana-loki --app $(kubectl get clusterapp -A -o json | jq -r '.items[] | select(.spec.appId? == "grafana-loki") | .metadata.name') -c grafana-loki-overrides -w kommander-workspace  -oyaml --dry-run | kubectl apply -f -